image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet add package HarperDb.Net.Client
      dornet add package AutoMapper 11.0.1
      dotnet add package AutoMapper.Extensions.Microsoft.DependencyInjection 11.0.0
      dotnet add package Newtonsoft.Json 13.0.1
      dotnet add package Swashbuckle.AspNetCore 5.6.3
      dotnet dev-certs https 
      dotnet restore
      dotnet build

vscode:
  extensions:
    - muhammad-sammy.csharp
    - esbenp.prettier-vscode
