image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet add package HarperDb.Net.Client
      dotnet dev-certs https 
      dotnet restore
      dotnet build

vscode:
  extensions:
    - muhammad-sammy.csharp
    - esbenp.prettier-vscode
